name: twodos_onboarding
description: "Twodos Onboarding"
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: 1.0.8
  flutter:
    sdk: flutter
  tactile_feedback:
    git: https://github.com/ksokolovskyi/tactile_feedback

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: 10.0.0

flutter:
  fonts:
    - family: SF Pro Rounded
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Regular.ttf
          weight: 400
        - asset: assets/fonts/SF-Pro-Rounded-Medium.ttf
          weight: 500

  uses-material-design: false
